language: java

jdk:
  - openjdk15

sudo: false

env:
  global:
    - CODECOV_TOKEN="b9d3a351-ed3b-4501-9b91-a6d2d06ab8bd"

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      ryslan.shuyski@mail.ru
    on_success: never # default: change
    on_failure: always # default: always